//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OMPIC_DBEntities : DbContext
    {
        public OMPIC_DBEntities()
            : base("name=OMPIC_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Brevets> Brevets { get; set; }
        public virtual DbSet<Domaines> Domaines { get; set; }
        public virtual DbSet<Entreprises> Entreprises { get; set; }
        public virtual DbSet<Inventeurs> Inventeurs { get; set; }
        public virtual DbSet<Inventions> Inventions { get; set; }
    }
}
